version: '3'

services:
  backend:
    build: backend
    ports:
      - 9000:9000

  frontend:
    build: frontend
    ports:
      - 8000:8000
    environment:
      - ENDPOINT=http://localhost:9000/api
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
