version: '3'

services:
  backend:
    build: backend
    ports:
      - 9000:9000
    environment:
      - FACEBOOK_APP_ID=39407e1c65185b097d80353ca7abbf8e

  frontend:
    build: frontend
    ports:
      - 8000:8000
    environment:
      - ENDPOINT=http://localhost:9000/api
